# Site settings
title: Divyanshi Kamra
email: divyanshi.kamra.1212@gmail.com
url: https://divyanshikamra.github.io
description: "Smily face, spirited soul and sharp-witted head, always looking for electrifying experiences and opportunities."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Divyanshi Kamra

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/divyanshi.kamra/
  - title: facebook
    url: https://www.facebook.com/divyanshi.kamra.7
  - title: github
    url: https://github.com/divyanshikamra

# Build settings
markdown: kramdown
permalink: pretty
